# Generated by Django 2.2.3 on 2019-08-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_userinfo_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='roles',
        ),
    ]
