# Generated by Django 2.2.3 on 2019-08-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('sign', '0003_auto_20190821_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='该用户拥有的角色'),
        ),
    ]
