# Generated by Django 2.2.3 on 2019-08-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32, verbose_name='一级菜单名称')),
                ('icon', models.CharField(default='', max_length=32, verbose_name='菜单的图标样式')),
            ],
            options={
                'verbose_name': '一级菜单表',
                'verbose_name_plural': '一级菜单表',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色表', 'verbose_name_plural': '角色表'},
        ),
        migrations.AddField(
            model_name='role',
            name='title',
            field=models.CharField(default='', max_length=32, verbose_name='角色名称'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32, verbose_name='标题')),
                ('url', models.CharField(default='', max_length=255, verbose_name='含有正则表达式的URL，urls.py中配置的')),
                ('name', models.CharField(default='', max_length=32, unique=True, verbose_name='URL别名')),
                ('menu', models.ForeignKey(blank=True, help_text='该项不为空，则是二级菜单，为空时，pid不为空，是二级菜单中的按钮', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='所属菜单')),
                ('pid', models.ForeignKey(blank=True, help_text='自关联字段，二级菜单中的按钮，要设置pid，设置所属的二级菜单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_menu', to='rbac.Permission', verbose_name='所属的二级菜单')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='角色拥有的权限'),
        ),
    ]
