# Generated by Django 2.2.3 on 2019-08-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190821_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(default='', help_text='菜单的图标样式', max_length=32, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(default='', help_text='一级菜单名称', max_length=32, verbose_name='菜单名称'),
        ),
    ]
