# Generated by Django 2.2.3 on 2019-08-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0004_userinfo_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255, verbose_name='问题描述')),
                ('detail', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='问题创建时间')),
                ('start_deal_time', models.DateTimeField(blank=True, null=True, verbose_name='问题开始处理时间')),
                ('stop_deal_time', models.DateTimeField(blank=True, null=True, verbose_name='问题完成时间')),
                ('status', models.IntegerField(choices=[(1, '未处理'), (2, '处理中'), (3, '完成')], verbose_name='状态')),
                ('create_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_create_person', to='sign.UserInfo', verbose_name='问题提出人')),
                ('deal_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_deal_person', to='sign.UserInfo', verbose_name='问题处理人')),
            ],
        ),
    ]
