# Generated by Django 2.2.3 on 2019-08-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='create_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_create_person', to='sign.UserInfo', verbose_name='问题提出人'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='deal_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_deal_person', to='sign.UserInfo', verbose_name='问题处理人'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='detail',
            field=models.TextField(verbose_name='详情'),
        ),
    ]
