# Generated by Django 2.2.3 on 2019-08-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_userinfo_roles'),
        ('problem', '0002_auto_20190826_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': '问题记录表', 'verbose_name_plural': '问题记录表'},
        ),
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(verbose_name='详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_record_create_person', to='sign.UserInfo', verbose_name='问题跟进人')),
            ],
            options={
                'verbose_name': '问题记录表',
                'verbose_name_plural': '问题记录表',
            },
        ),
    ]
