# Generated by Django 2.2.3 on 2019-08-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_followuprecord_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuprecord',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_record_problem', to='problem.Problem', verbose_name='对应的问题'),
        ),
    ]
