# Generated by Django 2.2.3 on 2019-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190814_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='is_menu',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否是菜单'),
        ),
    ]
