# Generated by Django 2.2.3 on 2019-08-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='URL别名'),
        ),
    ]
