# Generated by Django 2.2.3 on 2019-08-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_permission_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='URL别名'),
        ),
    ]
