# Generated by Django 2.2.3 on 2019-08-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20190815_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
